accounts:
  - name: alice
    coins: ["20000token", "200000000clan"]
  - name: bob
    coins: ["10000token", "100000000clan"]
build:
  binary: "cland"
  main: "cmd/cland"
validator:
  name: alice
  staked: "100000000clan"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000clan"]
genesis:
  chain_id: "clan-localnet-1"
  app_state:
    staking:
      params:
        bond_denom: "clan"